dist: trusty
sudo: required
language: python
python: "2.7"

services:
  - docker

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io

install:
  - pip install ansible
  - ansible-galaxy install -r apb/requirements-travis.yml
  - ansible-playbook apb/playbooks/provision.yml --syntax-check

script:
  - cd apb && docker build -t openshiftlabs/cloudnative-workshop-v2-labs:$TRAVIS_COMMIT .

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag openshiftlabs/cloudnative-workshop-v2-apb:$TRAVIS_COMMIT quay.io/openshiftlabs/cloudnative-workshop-v2-apb:$TAG
  - docker push quay.io/openshiftlabs/cloudnative-workshop-v2-apb:$TAG